# AUTO-TAG Configuration

# Paths
paths:
  input_folder: '/app/data/input'
  output_folder: '/app/data/output'
  models_dir: '/app/models'

# Hardware Settings
hardware:
  use_gpu: true
  cuda_device_id: 0

# Model Settings
models:
  clip:
    path: '/app/models/clip_vit_b32.pth'
    architecture: 'ViT-B-32'
  yolo:
    path: '/app/models/yolov8n.pt'
    min_person_height: 40
  facenet:
    path: '/app/models/facenet_model.pth'

# Tagging Settings
tagging:
  mode: 'append'
  min_confidence_percent: 80